<a href="https://colab.research.google.com/github/waleedfiaz663-cpu/Python-Practice/blob/main/ArrayCreation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

arr1 = np.arange(1,11)

print(arr1)

print("")

arr2 = np.arange(1,10).reshape(3,3)

print(arr2)

print("")

arr3 = np.array([5,10,15,20,25])

print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 5 10 15 20 25]
