<a href="https://colab.research.google.com/github/waleedfiaz663-cpu/Python-Practice/blob/main/Array%2CValues%2CDatatype%2CShape%2C2DArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

print("Array Values : ",arr1)
print("DataType : ",arr1.dtype)
print("Array Shape : " ,arr1.shape)

print("")

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array : ")
print(arr2)


Array Values :  [10 20 30 40 50]
DataType :  int64
Array Shape :  (5,)

2D Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
