<a href="https://colab.research.google.com/github/waleedfiaz663-cpu/Python-Practice/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

print("1D Array : ")

arr1D = np.array([10,20,30,40,50])

print("")



arr2D = np.array(([1,2,3],
                [4,5,6],
                [7,8,9]))

print("")

print(arr1D)

print("")

print("2D Array : ")

print("")

print(arr2D)

print("")

print("Shape of 1D Arrray : ")

print("")

print(arr1D.shape)

print("")

print("Shape of 2D Array : ")

print("")

print(arr2D.shape)

1D Array : 


[10 20 30 40 50]

2D Array : 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of 1D Arrray : 

(5,)

Shape of 2D Array : 

(3, 3)
