<a href="https://colab.research.google.com/github/waleedfiaz663-cpu/Python-Practice/blob/main/ReshapingArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np

arr = np.arange(1,13)

matrix_3x4 = np.reshape(arr,(3,4))

matrix_4x3 = np.reshape(arr,(4,3))

print("Original Array : ")

print("")

print(arr)

print("")

print("3x4 Matrix : ")

print("")

print(matrix_3x4)

print("")

print("4x3 Mattrix : ")

print("")

print(matrix_4x3)

Original Array : 

[ 1  2  3  4  5  6  7  8  9 10 11 12]

3x4 Matrix : 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

4x3 Mattrix : 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
