<a href="https://colab.research.google.com/github/waleedfiaz663-cpu/Python-Practice/blob/main/SpecialArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np

print(np.zeros(5))

print("")

print(np.ones(5))

print("")

print(np.eye(4))

print("")

print(np.arange(2,21,2))



[0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1.]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[ 2  4  6  8 10 12 14 16 18 20]
